///let age=21;
//let message=age>=18 ?"you are an adult":"you are a minor";
//console.log(message);
//let time=16;
//let greeting=time<12 ?"good morning":"good afternoon";
//console.log(greeting);
//let isstudent=true;
//let message=isstudent?"you are a student":"you are not a student";
//console.log(message);
let purschaseamount=125;
let discount=purschaseamount>=100? 10:0;
console.log(`you're total is $${purschaseamount-purschaseamount*(discount/100)}`);